@startuml
autonumber

boundary    "FBS" as fbs
boundary    "Service Platformen" as serviceplatformen

fbs -> serviceplatformen: Validér CPR-nummer.
serviceplatformen --> fbs: CPR-nummeret er validt.

@enduml
