@startuml
autonumber

actor user
boundary "DDB CMS" as cms
boundary "Adgangsplatformen" as login

user -> cms : "Click login button"
cms -> login : "Redirect"
login -> user : "Prompt for login"
user -> login : "Enter credentials and login"
login -> cms : "User logged in"
cms -> user : "Wellcome"
@enduml
