name: generate plantuml
on: push
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 10
    - name: plantuml
      id: plantuml
      uses: DDBdrift/generate-plantuml-action@DDBdrift-patch-1
      with:
        path: docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
